name = "BluseBeamformerRecipes"
uuid = "c979d30c-c9f2-448b-a26f-48ad51edd7af"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
